/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ealcaraz' at '11/30/16 2:03 PM' with Gradle 3.1
 *
 * @author ealcaraz, @date 11/30/16 2:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
